// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/api.proto

package common

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_71edda3932b293bf, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Company              string   `protobuf:"bytes,2,opt,name=Company,proto3" json:"Company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_71edda3932b293bf, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type UserList struct {
	List                 []*User  `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_71edda3932b293bf, []int{2}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetList() []*User {
	if m != nil {
		return m.List
	}
	return nil
}

type DispatchRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Company              string   `protobuf:"bytes,2,opt,name=Company,proto3" json:"Company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DispatchRequest) Reset()         { *m = DispatchRequest{} }
func (m *DispatchRequest) String() string { return proto.CompactTextString(m) }
func (*DispatchRequest) ProtoMessage()    {}
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71edda3932b293bf, []int{3}
}

func (m *DispatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DispatchRequest.Unmarshal(m, b)
}
func (m *DispatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DispatchRequest.Marshal(b, m, deterministic)
}
func (m *DispatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DispatchRequest.Merge(m, src)
}
func (m *DispatchRequest) XXX_Size() int {
	return xxx_messageInfo_DispatchRequest.Size(m)
}
func (m *DispatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DispatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DispatchRequest proto.InternalMessageInfo

func (m *DispatchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DispatchRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type Department struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Department) Reset()         { *m = Department{} }
func (m *Department) String() string { return proto.CompactTextString(m) }
func (*Department) ProtoMessage()    {}
func (*Department) Descriptor() ([]byte, []int) {
	return fileDescriptor_71edda3932b293bf, []int{4}
}

func (m *Department) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Department.Unmarshal(m, b)
}
func (m *Department) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Department.Marshal(b, m, deterministic)
}
func (m *Department) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Department.Merge(m, src)
}
func (m *Department) XXX_Size() int {
	return xxx_messageInfo_Department.Size(m)
}
func (m *Department) XXX_DiscardUnknown() {
	xxx_messageInfo_Department.DiscardUnknown(m)
}

var xxx_messageInfo_Department proto.InternalMessageInfo

func (m *Department) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Department) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type DepartmentList struct {
	List                 []*Department `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DepartmentList) Reset()         { *m = DepartmentList{} }
func (m *DepartmentList) String() string { return proto.CompactTextString(m) }
func (*DepartmentList) ProtoMessage()    {}
func (*DepartmentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_71edda3932b293bf, []int{5}
}

func (m *DepartmentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartmentList.Unmarshal(m, b)
}
func (m *DepartmentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartmentList.Marshal(b, m, deterministic)
}
func (m *DepartmentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartmentList.Merge(m, src)
}
func (m *DepartmentList) XXX_Size() int {
	return xxx_messageInfo_DepartmentList.Size(m)
}
func (m *DepartmentList) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartmentList.DiscardUnknown(m)
}

var xxx_messageInfo_DepartmentList proto.InternalMessageInfo

func (m *DepartmentList) GetList() []*Department {
	if m != nil {
		return m.List
	}
	return nil
}

type PersonChangeRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Company              string   `protobuf:"bytes,2,opt,name=Company,proto3" json:"Company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonChangeRequest) Reset()         { *m = PersonChangeRequest{} }
func (m *PersonChangeRequest) String() string { return proto.CompactTextString(m) }
func (*PersonChangeRequest) ProtoMessage()    {}
func (*PersonChangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71edda3932b293bf, []int{6}
}

func (m *PersonChangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonChangeRequest.Unmarshal(m, b)
}
func (m *PersonChangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonChangeRequest.Marshal(b, m, deterministic)
}
func (m *PersonChangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonChangeRequest.Merge(m, src)
}
func (m *PersonChangeRequest) XXX_Size() int {
	return xxx_messageInfo_PersonChangeRequest.Size(m)
}
func (m *PersonChangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonChangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PersonChangeRequest proto.InternalMessageInfo

func (m *PersonChangeRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PersonChangeRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "common.Empty")
	proto.RegisterType((*User)(nil), "common.User")
	proto.RegisterType((*UserList)(nil), "common.UserList")
	proto.RegisterType((*DispatchRequest)(nil), "common.DispatchRequest")
	proto.RegisterType((*Department)(nil), "common.Departments")
	proto.RegisterType((*DepartmentList)(nil), "common.DepartmentList")
	proto.RegisterType((*PersonChangeRequest)(nil), "common.PersonChangeRequest")
}

func init() {
	proto.RegisterFile("common/api.proto", fileDescriptor_71edda3932b293bf)
}

var fileDescriptor_71edda3932b293bf = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xbb, 0x4e, 0xc3, 0x40,
	0x10, 0x94, 0x43, 0x5e, 0x2c, 0x01, 0xa2, 0x45, 0x02, 0x2b, 0x34, 0x96, 0x0b, 0x88, 0x78, 0x04,
	0xc9, 0x50, 0x20, 0x1a, 0x84, 0x12, 0x3a, 0x40, 0x10, 0xc4, 0x07, 0x1c, 0xc9, 0x2a, 0x71, 0x71,
	0x0f, 0xee, 0x0e, 0xa4, 0x7c, 0x0c, 0x3f, 0xc1, 0x17, 0x22, 0x9f, 0x39, 0x92, 0x38, 0xa6, 0xa0,
	0xb2, 0xbd, 0xb3, 0xb3, 0x3b, 0x33, 0x6b, 0x68, 0x8f, 0x24, 0xe7, 0x52, 0x9c, 0x31, 0x95, 0xf6,
	0x94, 0x96, 0x56, 0x62, 0x3d, 0xaf, 0xc4, 0x0d, 0xa8, 0xdd, 0x72, 0x65, 0x67, 0xf1, 0x05, 0x54,
	0x5f, 0x0c, 0x69, 0x44, 0xa8, 0x3e, 0x30, 0x4e, 0x61, 0x10, 0x05, 0xdd, 0xf5, 0xa1, 0x7b, 0xc7,
	0x10, 0x1a, 0x7d, 0xc9, 0x15, 0x13, 0xb3, 0xb0, 0xe2, 0xca, 0xfe, 0x33, 0x3e, 0x81, 0x66, 0xc6,
	0xba, 0x4b, 0x8d, 0xc5, 0x08, 0xaa, 0xd9, 0x33, 0x0c, 0xa2, 0xb5, 0xee, 0x46, 0xd2, 0xea, 0xe5,
	0x1b, 0x7a, 0x19, 0x3e, 0x74, 0x48, 0x7c, 0x0d, 0xdb, 0x83, 0xd4, 0x28, 0x66, 0x47, 0xd3, 0x21,
	0xbd, 0xbd, 0x93, 0xb1, 0xff, 0x5c, 0x37, 0x00, 0x18, 0x90, 0x62, 0xda, 0x72, 0x12, 0xe5, 0xdc,
	0x18, 0x6a, 0xd9, 0x42, 0x13, 0x56, 0x4a, 0x54, 0xe4, 0x50, 0x7c, 0x09, 0x5b, 0xf3, 0x29, 0x4e,
	0xfa, 0xc1, 0x92, 0x74, 0xf4, 0xa4, 0x79, 0xd7, 0x8f, 0x81, 0x27, 0xd8, 0x79, 0x24, 0x6d, 0xa4,
	0xe8, 0x4f, 0x99, 0x98, 0x90, 0x37, 0x11, 0xe5, 0xd9, 0x39, 0x21, 0x2b, 0xce, 0x5d, 0xaa, 0x7f,
	0x5a, 0x4a, 0x3e, 0x03, 0xc0, 0xac, 0xe5, 0x9e, 0x09, 0x36, 0x21, 0xfd, 0x4c, 0xfa, 0x23, 0x1d,
	0x11, 0x1e, 0xe6, 0x8a, 0x70, 0xd3, 0x0f, 0x73, 0x57, 0xea, 0xb4, 0x17, 0x67, 0xbb, 0x86, 0x23,
	0x68, 0xdc, 0x8c, 0xc7, 0x6e, 0xc9, 0x0a, 0xd8, 0x59, 0x66, 0x63, 0x02, 0x4d, 0x9f, 0x3f, 0xee,
	0xfd, 0x9a, 0x5c, 0xbe, 0x48, 0x81, 0x93, 0x7c, 0x05, 0x10, 0xce, 0x73, 0x28, 0xa8, 0x3c, 0x2d,
	0x57, 0xb9, 0xbb, 0x1a, 0xa0, 0x6b, 0x3b, 0x86, 0x7a, 0x5f, 0x13, 0xb3, 0x84, 0x25, 0x11, 0x17,
	0xc5, 0x5e, 0x41, 0x6b, 0x31, 0x6b, 0xdc, 0xf7, 0x70, 0xc9, 0x05, 0x0a, 0xdc, 0xd7, 0xba, 0xfb,
	0xc9, 0xcf, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x85, 0x0f, 0x8b, 0xf8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserManagerServiceClient is the client API for UserManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserManagerServiceClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserList, error)
	AddUser(ctx context.Context, in *UserList, opts ...grpc.CallOption) (*Empty, error)
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*Empty, error)
}

type userManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserManagerServiceClient(cc grpc.ClientConnInterface) UserManagerServiceClient {
	return &userManagerServiceClient{cc}
}

func (c *userManagerServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserList, error) {
	out := new(UserList)
	err := c.cc.Invoke(ctx, "/common.UserManagerService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagerServiceClient) AddUser(ctx context.Context, in *UserList, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/common.UserManagerService/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagerServiceClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/common.UserManagerService/Dispatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManagerServiceServer is the server API for UserManagerService service.
type UserManagerServiceServer interface {
	List(context.Context, *Empty) (*UserList, error)
	AddUser(context.Context, *UserList) (*Empty, error)
	Dispatch(context.Context, *DispatchRequest) (*Empty, error)
}

// UnimplementedUserManagerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserManagerServiceServer struct {
}

func (*UnimplementedUserManagerServiceServer) List(ctx context.Context, req *Empty) (*UserList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedUserManagerServiceServer) AddUser(ctx context.Context, req *UserList) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedUserManagerServiceServer) Dispatch(ctx context.Context, req *DispatchRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dispatch not implemented")
}

func RegisterUserManagerServiceServer(s *grpc.Server, srv UserManagerServiceServer) {
	s.RegisterService(&_UserManagerService_serviceDesc, srv)
}

func _UserManagerService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.UserManagerService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagerService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.UserManagerService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServiceServer).AddUser(ctx, req.(*UserList))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagerService_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServiceServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.UserManagerService/Dispatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServiceServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.UserManagerService",
	HandlerType: (*UserManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _UserManagerService_List_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _UserManagerService_AddUser_Handler,
		},
		{
			MethodName: "Dispatch",
			Handler:    _UserManagerService_Dispatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/api.proto",
}

// DepartmentManagerServiceClient is the client API for DepartmentManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DepartmentManagerServiceClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DepartmentList, error)
	Create(ctx context.Context, in *Department, opts ...grpc.CallOption) (*Empty, error)
	PersonChange(ctx context.Context, in *PersonChangeRequest, opts ...grpc.CallOption) (*Empty, error)
}

type departmentManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDepartmentManagerServiceClient(cc grpc.ClientConnInterface) DepartmentManagerServiceClient {
	return &departmentManagerServiceClient{cc}
}

func (c *departmentManagerServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DepartmentList, error) {
	out := new(DepartmentList)
	err := c.cc.Invoke(ctx, "/common.DepartmentManagerService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentManagerServiceClient) Create(ctx context.Context, in *Department, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/common.DepartmentManagerService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentManagerServiceClient) PersonChange(ctx context.Context, in *PersonChangeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/common.DepartmentManagerService/PersonChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepartmentManagerServiceServer is the server API for DepartmentManagerService service.
type DepartmentManagerServiceServer interface {
	List(context.Context, *Empty) (*DepartmentList, error)
	Create(context.Context, *Department) (*Empty, error)
	PersonChange(context.Context, *PersonChangeRequest) (*Empty, error)
}

// UnimplementedDepartmentManagerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDepartmentManagerServiceServer struct {
}

func (*UnimplementedDepartmentManagerServiceServer) List(ctx context.Context, req *Empty) (*DepartmentList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedDepartmentManagerServiceServer) Create(ctx context.Context, req *Department) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedDepartmentManagerServiceServer) PersonChange(ctx context.Context, req *PersonChangeRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PersonChange not implemented")
}

func RegisterDepartmentManagerServiceServer(s *grpc.Server, srv DepartmentManagerServiceServer) {
	s.RegisterService(&_DepartmentManagerService_serviceDesc, srv)
}

func _DepartmentManagerService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentManagerServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.DepartmentManagerService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentManagerServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentManagerService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Department)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentManagerServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.DepartmentManagerService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentManagerServiceServer).Create(ctx, req.(*Department))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentManagerService_PersonChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentManagerServiceServer).PersonChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.DepartmentManagerService/PersonChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentManagerServiceServer).PersonChange(ctx, req.(*PersonChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DepartmentManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.DepartmentManagerService",
	HandlerType: (*DepartmentManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _DepartmentManagerService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _DepartmentManagerService_Create_Handler,
		},
		{
			MethodName: "PersonChange",
			Handler:    _DepartmentManagerService_PersonChange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/api.proto",
}
